=== wkm/Axirassa/src/main/java/axirassa/overlord/AxOverlord-Configuration-1.0.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT configuration (target+, group+)>

<!ELEMENT target (jvmoption*,library*)>
<!ATTLIST target 
	name CDATA #REQUIRED
	class CDATA #REQUIRED
	autorestart (yes|no) "yes"
	launchmode (jvm|thread) "jvm"
>

<!ELEMENT jvmoption EMPTY>
<!ATTLIST jvmoption
	 name CDATA #REQUIRED
	 value CDATA #REQUIRED
>

<!ELEMENT library (#PCDATA)>

<!ELEMENT group (execute+)>
<!ATTLIST group
	name CDATA #REQUIRED
>

<!ELEMENT execute (#PCDATA)>
<!ATTLIST execute 
	 target CDATA #REQUIRED
	 instances CDATA "1"
	 initialdelay CDATA "0"
>

=== wkm/Axirassa/src/main/resources/axoverlord.cfg.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE axoverlord-configuration PUBLIC
	"-//AxOverlord/AxOverlord Configuration DTD 1.0//EN"
	"com/zanoccio/axirassa/overlord/AxOverlord-Configuration-1.0.dtd">
<configuration>
	<target name="AxSentinelAgent" class=""/>
	<target name="AxSobrietyQ" />
	<target name="AxMessageQ" />
	
	<group name="master">
		<execute>AxSentinelAgent</execute>
		<execute>AxSentinelQ</execute>
		<execute>AxMessageQ</execute>
	</group>
	
	<group name="worker">
		<execute>AxSentinelAgent</execute>
		<execute instances="6">AxPinger</execute>
	</group>
	
	<group name="support">
		<execute>AxSentinelAgent</execute>
		<execute instances="3">AxEmailService</execute>
		<execute instances="3">AxSMSService</execute>
	</group>
</configuration>
